apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
  namespace: dev
data:
  SERVICE_NAME: "order-api"
  ENVIRONMENT: "dev"
  PORT: "3000"
  # Service discovery within the namespace — this is the Kubernetes Service DNS name
  ALERTING_SERVICE_URL: "http://alerting-service:3001"