CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(50) PRIMARY KEY,
  item VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL,
  environment VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id VARCHAR(50) PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  order_id VARCHAR(50) REFERENCES orders(id) ON DELETE SET NULL,
  item VARCHAR(255),
  environment VARCHAR(50) NOT NULL,
  source VARCHAR(100),
  received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
