apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: order-tracker-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Joyaroin/Order-Tracker-DevOps-Project.git
        revision: HEAD
        directories:
          - path: k8s/overlays/*
  template:
    metadata:
      name: 'order-tracker-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Joyaroin/Order-Tracker-DevOps-Project.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
