apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kafka
    targetRevision: 32.2.8
    helm:
      values: |
        kraft:
          enabled: true
        controller:
          replicaCount: 1
        broker:
          replicaCount: 1
        listeners:
          client:
            protocol: PLAINTEXT
          controller:
            protocol: PLAINTEXT
        provisioning:
          enabled: true
          topics:
            - name: orders-dev
              partitions: 1
              replicationFactor: 1
            - name: orders-staging
              partitions: 1
              replicationFactor: 1
        persistence:
          storageClass: gp2
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
