apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hotfix-test-ephemeral-env

resources:
  - ../../base
  - order-api-configmap.yaml
  - alerting-service-configmap.yaml
  - frontend-configmap.yaml

images:
  - name: order-api
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/order-api
    newTag: "e91aff304f2e1eef9d0e7611c49c2f2530845f22"
  - name: alerting-service
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/alerting-service
    newTag: "e91aff304f2e1eef9d0e7611c49c2f2530845f22"
  - name: frontend
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/frontend
    newTag: "e91aff304f2e1eef9d0e7611c49c2f2530845f22"

patches:
  - target:
      kind: Deployment
      name: order-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Service
      name: frontend
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
