apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "ordertracker"
  DB_NAME: "ordertracker_dev"
  DB_SSL: "true"
