apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - order-api-configmap.yaml
  - alerting-service-configmap.yaml
  - frontend-configmap.yaml

images:
  - name: order-api
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/order-api
    newTag: "2e0571ee7e8aedf69f4d40b6b54776a5fa21a695"
  - name: alerting-service
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/alerting-service
    newTag: "2e0571ee7e8aedf69f4d40b6b54776a5fa21a695"
  - name: frontend
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/frontend
    newTag: "2e0571ee7e8aedf69f4d40b6b54776a5fa21a695"

patches:
  - target:
      kind: Deployment
      name: order-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Service
      name: frontend
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
