apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - order-api-configmap.yaml
  - alerting-service-configmap.yaml
  - frontend-configmap.yaml

images:
  - name: order-api
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/order-api
    newTag: "afcd46cc04d2cb95b18d792a8fc18264241204c3"
  - name: alerting-service
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/alerting-service
    newTag: "afcd46cc04d2cb95b18d792a8fc18264241204c3"
  - name: frontend
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/frontend
    newTag: "afcd46cc04d2cb95b18d792a8fc18264241204c3"

patches:
  - target:
      kind: Deployment
      name: order-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Service
      name: frontend
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
