apiVersion: v1
kind: ConfigMap
metadata:
  name: alerting-service-config
data:
  SERVICE_NAME: "alerting-service"
  ENVIRONMENT: "staging"
  PORT: "3001"
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "orders-staging"
  KAFKA_GROUP_ID: "alerting-service-staging"
  DB_HOST: "postgres-postgresql.staging.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "ordertracker"
  DB_NAME: "ordertracker"
