apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - order-api-configmap.yaml
  - alerting-service-configmap.yaml
  - frontend-configmap.yaml

images:
  - name: order-api
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/order-api
    newTag: "13b64f47aa71646e6df2e9467113c230d796782e"
  - name: alerting-service
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/alerting-service
    newTag: "13b64f47aa71646e6df2e9467113c230d796782e"
  - name: frontend
    newName: 284495577709.dkr.ecr.us-east-2.amazonaws.com/frontend
    newTag: "13b64f47aa71646e6df2e9467113c230d796782e"

patches:
  - target:
      kind: Service
      name: frontend
    patch: |
      - op: replace
        path: /spec/type
        value: LoadBalancer
