apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-config
data:
  SERVICE_NAME: "order-api"
  ENVIRONMENT: "staging"
  PORT: "3000"
  ALERTING_SERVICE_URL: "http://alerting-service:3001"
  KAFKA_BROKERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_TOPIC: "orders-staging"
