#!/usr/bin/env bash
# Regenerate artifacts/<env>.yaml from k8s/overlays/<env>/kustomization.yaml.
# Read-only: never touches deployment state.

set -euo pipefail

cd "$(dirname "$0")/.."

for env in dev staging; do
  overlay="k8s/overlays/$env/kustomization.yaml"
  out="artifacts/$env.yaml"

  if [[ ! -f "$overlay" ]]; then
    echo "skip: $overlay missing" >&2
    continue
  fi

  generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  {
    echo "# Auto-generated by artifacts/refresh.sh — do not edit by hand."
    echo "environment: $env"
    echo "source: $overlay"
    echo "generatedAt: $generated_at"
    echo "images:"

    awk '
      /^  - name:/ {
        name = $3
        next
      }
      /^    newName:/ {
        repo = $2
        next
      }
      /^    newTag:/ {
        tag = $2
        gsub(/"/, "", tag)
        printf "  - service: %s\n", name
        printf "    repository: %s\n", repo
        printf "    tag: %s\n", tag
        printf "    ref: %s:%s\n", repo, tag
      }
    ' "$overlay"
  } > "$out"

  echo "wrote $out"
done
